// Code generated by "stringer -type Charset -linecomment"; DO NOT EDIT.

package escpos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharsetUnitedStates-2]
	_ = x[CharsetFrance-3]
	_ = x[CharsetGermany-4]
	_ = x[CharsetUnitedKingdom-5]
	_ = x[CharsetDenmark1-6]
	_ = x[CharsetSweden-7]
	_ = x[CharsetItaly-8]
	_ = x[CharsetSpain1-9]
	_ = x[CharsetJapan-10]
	_ = x[CharsetNorway-11]
	_ = x[CharsetDenmark2-12]
	_ = x[CharsetSpain2-13]
	_ = x[CharsetLatinAmerica-14]
}

const _Charset_name = "U.S.A.FranceGermanyU.K.Denmark ISwedenItalySpain IJapanNorwayDenmark IISpain IILatin America"

var _Charset_index = [...]uint8{0, 6, 12, 19, 23, 32, 38, 43, 50, 55, 61, 71, 79, 92}

func (i Charset) String() string {
	i -= 2
	if i >= Charset(len(_Charset_index)-1) {
		return "Charset(" + strconv.FormatInt(int64(i+2), 10) + ")"
	}
	return _Charset_name[_Charset_index[i]:_Charset_index[i+1]]
}
