// Code generated by "stringer -type Font -trimprefix Font"; DO NOT EDIT.

package escpos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FontA-0]
	_ = x[FontB-1]
}

const _Font_name = "AB"

var _Font_index = [...]uint8{0, 1, 2}

func (i Font) String() string {
	if i >= Font(len(_Font_index)-1) {
		return "Font(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Font_name[_Font_index[i]:_Font_index[i+1]]
}
