// Code generated by "stringer -type Justification -trimprefix Justify"; DO NOT EDIT.

package escpos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JustifyLeft-0]
	_ = x[JustifyCenter-1]
	_ = x[JustifyRight-2]
}

const _Justification_name = "LeftCenterRight"

var _Justification_index = [...]uint8{0, 4, 10, 15}

func (i Justification) String() string {
	if i >= Justification(len(_Justification_index)-1) {
		return "Justification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Justification_name[_Justification_index[i]:_Justification_index[i+1]]
}
