// Code generated by "stringer -type PrintMode -trimprefix With"; DO NOT EDIT.

package escpos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WithAlternateFont-1]
	_ = x[WithEmphasis-8]
	_ = x[WithDoubleHeight-16]
	_ = x[WithDoubleWidth-32]
	_ = x[WithUnderline-128]
}

const (
	_PrintMode_name_0 = "AlternateFont"
	_PrintMode_name_1 = "Emphasis"
	_PrintMode_name_2 = "DoubleHeight"
	_PrintMode_name_3 = "DoubleWidth"
	_PrintMode_name_4 = "Underline"
)

func (i PrintMode) String() string {
	switch {
	case i == 1:
		return _PrintMode_name_0
	case i == 8:
		return _PrintMode_name_1
	case i == 16:
		return _PrintMode_name_2
	case i == 32:
		return _PrintMode_name_3
	case i == 128:
		return _PrintMode_name_4
	default:
		return "PrintMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
