// Code generated by "stringer -type PrintDirection -trimprefix Print"; DO NOT EDIT.

package escpos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrintLeftToRight-0]
	_ = x[PrintBottomToTop-1]
	_ = x[PrintRightToLeft-2]
	_ = x[PrintTopToBottom-3]
}

const _PrintDirection_name = "LeftToRightBottomToTopRightToLeftTopToBottom"

var _PrintDirection_index = [...]uint8{0, 11, 22, 33, 44}

func (i PrintDirection) String() string {
	if i >= PrintDirection(len(_PrintDirection_index)-1) {
		return "PrintDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrintDirection_name[_PrintDirection_index[i]:_PrintDirection_index[i+1]]
}
