// Code generated by "stringer -type Underline -trimprefix Underline"; DO NOT EDIT.

package escpos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnderlineNone-0]
	_ = x[UnderlineSingle-1]
	_ = x[UnderlineDouble-2]
}

const _Underline_name = "NoneSingleDouble"

var _Underline_index = [...]uint8{0, 4, 10, 16}

func (i Underline) String() string {
	if i >= Underline(len(_Underline_index)-1) {
		return "Underline(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Underline_name[_Underline_index[i]:_Underline_index[i+1]]
}
